spring:
  application:
    name: api-challenge
  datasource:
    url: jdbc:postgresql://postgres:5432/mydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

cl:
  tenpo:
    challenge:
      cache:
        key-name: percent